### ISSUE TITLE
JACK-to-VST audio

### ISSUE THREAD

**Issue by KottV** [falkTX/JackAss#3]
Hi,

Just curious, is it have a sense (and possibility in future) to plug JackAss audio to VST host back?
I think you know what i mean: start some synth, plug midi in via JackaAss then plug audio out to JackAss, so it would look like VST Synth :)

**Comment by gwatcha** [comment]
I also have this question!

**Comment by falkTX** [comment]
This is out of scope for this plugin.

While possible in theory, such plugin will always have additional latency.
In any case, It will not be part of the JackAss project
