### ISSUE TITLE
JackAssFX segfaults when exiting Radium

### ISSUE THREAD

**Issue by kmatheussen** [falkTX/JackAss#4]
If I have some spare time I might compile jackass manually to get debug symbols.

```
[Switching to Thread 0x7fff50c9d700 (LWP 20082)]
0x00007fff5098fe77 in ?? () from /home/kjetil/.vst/linux64/JackAssFx.so
(gdb) bt
#0  0x00007fff5098fe77 in ?? () from /home/kjetil/.vst/linux64/JackAssFx.so
#1  0x00007ffff1c1ec22 in Jack::JackClient::CallProcessCallback() () from /lib64/libjack.so.0
#2  0x00007ffff1c1eb2a in Jack::JackClient::ExecuteThread() () from /lib64/libjack.so.0
#3  0x00007ffff1c1c741 in Jack::JackClient::Execute() () from /lib64/libjack.so.0
#4  0x00007ffff1c3c710 in Jack::JackPosixThread::ThreadHandler(void*) () from /lib64/libjack.so.0
#5  0x00007fffecd24ee5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fffeca53d1d in clone () from /lib64/libc.so.6
```

**Comment by kmatheussen** [comment]
When running non-debug version of Radium, Radium also crashes at exit when JackAssFX is loaded, and I get this error in the terminal:
```
jack_port_get_buffer called with an incorrect port 805342096
```

Other VST plugins don't crash at exit so I think Radium cleans up VST plugins correctly before exiting, but of course it could be a bug in Radium too.

**Comment by falkTX** [comment]
This seems like a race condition. I will add a mutex to see if it makes things better

**Comment by falkTX** [comment]
Ok please try 275f21b4aa3a34da0c3f7f1a6c734880f50a360b and let me know if that improves anything

**Comment by kmatheussen** [comment]
Doesn't seem to make a difference.

With lock:
```
Thread 24 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff52118700 (LWP 26403)]
Cannot remove breakpoints because program is no longer writable.
Further execution is probably impossible.
jprocess_callback (nframes=<error reading variable: Cannot access memory at address 0x7fff52117a8c>) at JackAss.cpp:186
186             (*it)->jprocess(nframes);
```

Without lock:
```

Thread 24 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff8b170700 (LWP 26739)]
Cannot remove breakpoints because program is no longer writable.
Further execution is probably impossible.
jprocess_callback (nframes=<error reading variable: Cannot access memory at address 0x7fff8b16fa8c>) at JackAss.cpp:186
186             (*it)->jprocess(nframes);
```

**Comment by kmatheussen** [comment]
Sorry, it's a bug in Radium. It's caused by a workaround for OSX where you have to delay the deletion of the plugin for a few seconds after closing a native GUI window. The mutex you added seems correct though.

**Comment by kmatheussen** [comment]
(here's a discussion about the thing causing crashes on OSX if closing plugin directly after closing the GUI, for anyone interested: https://forum.juce.com/t/crashes-when-close-app-mac-once-in-a-while/12902)

**Comment by falkTX** [comment]
oh wow, yeah that is painful.
FYI I do the same for Carla on macOS too. Seems we cant delete plugins right after closing their GUI. very odd
